name: Build & Deploy (Staging)

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Configure npm shell
        run: npm config set script-shell /bin/bash

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Build
        run: npm run build
        env:
          REACT_APP_SERVER_URL: ${{ secrets.REACT_APP_SERVER_URL }}
          REACT_APP_SENTRY_DSN: ${{ secrets.REACT_APP_SENTRY_DSN }}
          REACT_APP_BASE: staging
          REACT_APP_SENTRY_ENV: staging
          PUBLIC_URL: /staging/central
          NPM_CONFIG_SCRIPT_SHELL: /bin/bash
          CI: false

      - name: Deploy build to server via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: build/
          target: ${{ secrets.STAGING_PATH }}
          strip_components: 1
